### ISSUE TITLE
[Code Review Request] BraillePy

### ISSUE THREAD

**Issue by UltraStudioLTD** [willmcgugan/codereviews#2]
**What is the name of your project?**
Braille as Python Module and BraillePy as repository

**What is the repo URL?**
https://github.com/UltraStudioLTD/BraillePy

**Is there anything else I should know about the code?**
If you use Python <3.5 then you must install "typing" module.

**Are there any areas you would like me to focus on?**
Will it be usable? I mean does it have any potential? Also is it possible to make it faster and more simpler?

**Is this your first review?**
Yes.

- [x] I agree for the code review to be public

**Comment by willmcgugan** [comment]
I'd say, yes definitely, it has a lot of potential. I'm sure someone will need this functionality.

I don't think it will need to be much faster. I'd focus on the API right now. Kudos for implementing this!

Here's the review.

https://github.com/willmcgugan/codereviews/blob/main/reviews/BraillePy%201.md

Closing the issue, but you may still comment if you have questions.
