### ISSUE TITLE
Why r u doing this 4 free

### ISSUE THREAD

**Issue by ElDavoo** [willmcgugan/codereviews#22]
Just curious to know, you showed up in my Google feed

**Comment by dzek69** [comment]
Why thousands of people around the world contribute to open source? 🤔

**Comment by ElDavoo** [comment]
contribute to code or docs, but never heard about doing code reviews to random projects

**Comment by willmcgugan** [comment]
It’s my way of giving back. Also I may charge for commercial software, so I could use practice.
